name: prepare-environment
description: Prepares the environment
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      run: |
        mkdir -p ${{github.workspace}}/build
        sudo apt-get update
        sudo apt-get install -y tar
        sudo apt-get install -y wget
        sudo apt-get install -y cmake
        sudo apt-get install -y buildah
        sudo apt-get install -y ninja-build
        sudo apt-get install -y clang
        sudo apt-get install -y clang-tidy
        sudo apt-get install -y pkg-config
        sudo apt-get install -y build-essential
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt update
        sudo apt-get install -y intel-oneapi-base-toolkit
      shell: bash

